services:
  symvouloi:
    image: itdipeira/school_consultants:latest
    entrypoint: ["./docker-files/entrypoint.sh"]
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 180
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    build: ./docker-files
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 8080:80
    depends_on:
      - symvouloi

volumes:
  static_volume:
