# Generated by Django 5.1.3 on 2024-11-21 09:02

import django.db.models.deletion
import symvouloi.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Επώνυμο εκπ/κού')),
                ('teacher_first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Όνομα εκπ/κού')),
                ('teacher_afm', models.CharField(max_length=9, verbose_name='ΑΦΜ εκπαιδευτικού')),
                ('consultant_last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Επώνυμο συμβούλου')),
                ('consultant_first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Όνομα συμβούλου')),
                ('consultant_afm', models.CharField(max_length=9, verbose_name='ΑΦΜ συμβούλου')),
                ('loaded', models.BooleanField(default=False, verbose_name='Καταχωρήθηκε')),
                ('comments', models.CharField(blank=True, max_length=300, null=True, verbose_name='Σχόλια')),
            ],
            options={
                'verbose_name': 'Ανάθεση εκπαιδευτικού',
                'verbose_name_plural': 'Αναθέσεις εκπαιδευτικών',
            },
        ),
        migrations.CreateModel(
            name='EvaluationStepType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Βήμα Αξιολόγησης')),
            ],
            options={
                'verbose_name': 'Τύπος βήματος αξιολόγησης',
                'verbose_name_plural': 'Τύποι βημάτων αξιολόγησης',
                'constraints': [models.UniqueConstraint(fields=('title',), name='unique_evaluation_step_type')],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_year', models.CharField(max_length=10, verbose_name='Σχ. Έτος Αξιολόγησης')),
                ('afm', models.CharField(max_length=9, verbose_name='ΑΦΜ')),
                ('last_name', models.CharField(max_length=50, verbose_name='Επώνυμο')),
                ('first_name', models.CharField(max_length=50, verbose_name='Όνομα')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Πατρώνυμο')),
                ('specialty', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ειδικότητα')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='Σχολείο')),
                ('fek', models.CharField(blank=True, max_length=30, null=True, verbose_name='ΦΕΚ Διορισμού')),
                ('appointment_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Διορισμού')),
                ('mobile', models.CharField(blank=True, max_length=25, null=True, verbose_name='Κινητό')),
                ('mail', models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('participates', models.BooleanField(default=True, verbose_name='Συμμετέχει στην αξιολόγηση')),
                ('comments', models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Σχόλια')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργός εκπαιδευτικός')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluates_teachers', to=settings.AUTH_USER_MODEL, verbose_name='Σύμβουλος Εκπαίδευσης')),
            ],
            options={
                'verbose_name': 'Εκπαιδευτικός',
                'verbose_name_plural': 'Εκπαιδευτικοί',
            },
        ),
        migrations.CreateModel(
            name='EvaluationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_date', models.DateField(verbose_name='Ημερομηνία')),
                ('complete', models.BooleanField(default=False, verbose_name='Ολοκληρώθηκε')),
                ('evaluation_document', models.FileField(blank=True, null=True, upload_to=symvouloi.models.custom_documents_directory_path, verbose_name='Αρχείο Αξιολόγησης')),
                ('comments', models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Σχόλια')),
                ('timestamp', models.DateTimeField(verbose_name='Χρονική σήμανση')),
                ('downloaded', models.BooleanField(default=False, verbose_name='Έγινε λήψη')),
                ('approved', models.BooleanField(default=False, verbose_name='Ελέγχθηκε')),
                ('to_review', models.BooleanField(default=False, verbose_name='Για αναθεώρηση')),
                ('comments_from_director', models.TextField(blank=True, default='', max_length=200, null=True, verbose_name='Σχόλια Επόπτη Ποιότητας')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_evaluation_steps', to=settings.AUTH_USER_MODEL, verbose_name='Σύμβουλος Εκπαίδευσης')),
                ('es_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symvouloi.evaluationsteptype', verbose_name='Βήμα Αξιολόγησης')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_evaluation_steps', to='symvouloi.teacher', verbose_name='Εκπαιδευτικός')),
            ],
            options={
                'verbose_name': 'Βήμα αξιολόγησης',
                'verbose_name_plural': 'Βήματα αξιολόγησης',
                'constraints': [models.UniqueConstraint(fields=('consultant', 'teacher', 'es_type'), name='unique_evaluation_step')],
            },
        ),
    ]
