# Generated by Django 5.1.3 on 2025-01-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symvouloi', '0003_alter_evaluationstep_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_office_days', models.BooleanField(default=False, verbose_name='Εμφάνιση ημερών γραφείου')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='Διακομιστής αλληλογραφίας')),
                ('email_tls', models.BooleanField(default=True, verbose_name='Χρήση TLS')),
                ('email_port', models.IntegerField(default='587', verbose_name='Θύρα Διακομιστή αλληλογραφίας')),
                ('email_username', models.CharField(default='username', max_length=50, verbose_name='Όνομα χρήστη αλληλογραφίας')),
                ('email_password', models.CharField(default='password', max_length=50, verbose_name='Κωδικός χρήστη αλληλογραφίας')),
                ('email_from', models.CharField(default='', max_length=50, verbose_name='Email αποστολέα')),
                ('recipient_list', models.CharField(default='', max_length=255, verbose_name='Email παραληπτών (χωρισμένα με κόμμα)')),
            ],
            options={
                'verbose_name': 'Παράμετροι εφαρμογής',
            },
        ),
    ]
