# Generated by Django 5.1.3 on 2025-01-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symvouloi', '0004_siteconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email_from',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Email αποστολέα'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email_password',
            field=models.CharField(blank=True, default='password', max_length=50, null=True, verbose_name='Κωδικός χρήστη αλληλογραφίας'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email_username',
            field=models.CharField(blank=True, default='username', max_length=50, null=True, verbose_name='Όνομα χρήστη αλληλογραφίας'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='recipient_list',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Email παραληπτών (χωρισμένα με κόμμα)'),
        ),
    ]
