# Generated by Django 5.1.3 on 2025-01-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symvouloi', '0005_alter_siteconfiguration_email_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=255, null=True, verbose_name='Διακομιστής αλληλογραφίας'),
        ),
    ]
