# Generated by Django 5.1.3 on 2025-01-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symvouloi', '0006_alter_siteconfiguration_email_host'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
    ]
