# Generated by Django 5.1.3 on 2025-03-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symvouloi', '0010_evaluationdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationdata',
            options={'verbose_name': 'History', 'verbose_name_plural': 'History'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='category',
        ),
        migrations.AddField(
            model_name='evaluationstep',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('A1', 'A1'), ('A2', 'A2'), ('B', 'B')], max_length=5, null=True, verbose_name='Κατηγορία αξιολόγησης'),
        ),
    ]
