# Generated by Django 5.1.3 on 2025-03-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symvouloi', '0011_alter_evaluationdata_options_remove_teacher_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_permanent',
            field=models.BooleanField(default=False, verbose_name='Μονιμοποίηση'),
        ),
    ]
