# Generated by Django 5.1.3 on 2025-04-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symvouloi', '0012_teacher_is_permanent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationdata',
            options={'verbose_name': 'Iστορικό Αξιολόγησης', 'verbose_name_plural': 'Iστορικό Αξιολόγησης'},
        ),
    ]
