# Generated by Django 5.1.3 on 2025-11-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symvouloi', '0013_alter_evaluationdata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='categories',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Κατηγορίες αξιολόγησης'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('A1', 'A1'), ('A2', 'A2'), ('B', 'B')], max_length=10, null=True, verbose_name='Κατηγορία αξιολόγησης'),
        ),
    ]
