# Generated by Django 5.1.3 on 2025-11-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symvouloi', '0014_teacher_categories_teacherassignment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationstep',
            name='category',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B', 'B')], max_length=5, null=True, verbose_name='Κατηγορία αξιολόγησης'),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='category',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B', 'B')], max_length=10, null=True, verbose_name='Κατηγορία αξιολόγησης'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(fields=('teacher_afm', 'category'), name='unique_teacher_category_assignment'),
        ),
    ]
