# Generated by Django 5.1.3 on 2024-12-04 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metakinhsh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metak_from', models.CharField(max_length=100, verbose_name='Από')),
                ('metak_to', models.CharField(max_length=100, verbose_name='Προορισμός')),
                ('date_from', models.DateField(verbose_name='Ημ/νία Από')),
                ('date_to', models.DateField(null=True, verbose_name='Ημ/νία Έως')),
                ('km', models.IntegerField(verbose_name='Χιλιόμετρα')),
                ('egkrish', models.BooleanField(default=False, verbose_name='Έγκριση')),
                ('pragmat', models.BooleanField(default=False, verbose_name='Πραγματοποιήθηκε')),
                ('aitiologia', models.TextField(verbose_name='Αιτιολογία')),
                ('handler', models.CharField(blank=True, choices=[('Επόπτης', 'Επόπτης'), ('Οικονομικό', 'Οικονομικό')], default=None, max_length=80, null=True, verbose_name='Χειριστής')),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Μετακίνηση',
                'verbose_name_plural': 'Μετακινήσεις',
            },
        ),
    ]
