# Generated by Django 5.1.3 on 2024-12-20 10:19

import metakinhseis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakinhseis', '0002_metakinhsh_amount1_metakinhsh_amount2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metakinhsh',
            name='file',
            field=models.FileField(default='', null=True, upload_to=metakinhseis.models.custom_documents_directory_path, verbose_name='Αρχείο'),
        ),
    ]
