# Generated by Django 5.1.3 on 2024-12-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakinhseis', '0004_alter_metakinhsh_file_consultant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultant',
            options={'verbose_name': 'Σύμβουλος', 'verbose_name_plural': 'Σύμβουλοι'},
        ),
        migrations.AlterField(
            model_name='metakinhsh',
            name='km',
            field=models.FloatField(help_text='Παρακαλώ εισάγετε την απόσταση από το Α στο Β, όχι όλης της διαδρομής', verbose_name='Χιλιόμετρα'),
        ),
    ]
