# Generated by Django 5.1.3 on 2025-01-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakinhseis', '0007_consultant_am_consultant_iban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='am',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Αριθμός μητρώου'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='enothta',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Ενότητα'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='iban',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='klados',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Ειδικότητα'),
        ),
    ]
