# Generated by Django 5.1.3 on 2025-01-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakinhseis', '0009_officeschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officeschedule',
            options={'verbose_name': 'Ημέρα γραφείου', 'verbose_name_plural': 'Ημέρες γραφείου'},
        ),
        migrations.AlterField(
            model_name='officeschedule',
            name='days_in_office',
            field=models.JSONField(default=list, verbose_name='Ημέρες γραφείου'),
        ),
        migrations.AlterField(
            model_name='officeschedule',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Μήνας'),
        ),
    ]
