# Generated by Django 5.1.3 on 2025-09-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakinhseis', '0010_alter_officeschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metakinhsh',
            name='school_year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Σχολικό έτος'),
        ),
    ]
