# Generated by Django 5.1.3 on 2025-11-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metakinhseis', '0011_metakinhsh_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='metakinhsh',
            name='dyee',
            field=models.BooleanField(default=False, verbose_name='Προωθήθηκε στη ΔΥΕΕ'),
        ),
        migrations.AddField(
            model_name='metakinhsh',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Τελευταία ενημέρωση'),
        ),
        migrations.AlterField(
            model_name='metakinhsh',
            name='aitiologia',
            field=models.TextField(max_length=150, verbose_name='Αιτιολογία'),
        ),
    ]
